name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install Trunk
        run: cargo +nightly install trunk

      - name: Build and deploy
        run: |
          cd pages
          cargo +nightly build --target wasm32-unknown-unknown --release
          cargo +nightly install wasm-bindgen-cli
          trunk build --release
          trunk serve --open

